export const EVENT = {
  SOCKET_ID: 'socketId',
  CONNECT_CONTROLLER: 'connectController',
  CONNECT_CONTROLLER_SUCCESS: 'connectControllerSuccess',
  CONNECT_CONTROLLER_CALLBACK: 'connectControllerCallback',
  DISCONNECT_BY_USER: 'disconnectByUser',
  DISCONNECT_BY_USER_CALLBACK: 'disconnectByUserCallback',
  DISCONNECT_BY_CONTROLLER: 'disconnectByController',
  DISCONNECT_BY_CONTROLLER_CALLBACK: 'disconnectByControllerCallback',
  INVALID_USER_ID: 'invalidUserId',

  SEND_BETA: 'sendBeta',
  INVALID_SENSOR: 'invalidSensor',
  SEND_GAME_BETA: 'sendGameBeta',
  LEFT_ANGLE_CHECK: 'leftAngleCheck',
  RIGHT_ANGLE_CHECK: 'rightAngleCheck',
  FINISH_ANGLE_CHECK: 'finishAngleCheck',
  CLOSE_ANGLE_CHECK: 'closeAngleCheck',
  SET_MOTION: 'setMotion',
  RESET_MOTION_DATA: 'resetMotionData',
  SEND_MOTION_UP: 'sendMotionUp',
  SEND_MOTION_DOWN: 'sendMotionDown',
  SEND_MOTION_LEFT: 'sendMotionLeft',
  SEND_MOTION_RIGHT: 'sendMotionRight',
  RESET_ANGLE: 'resetAngle',
  ANGLE_INFO: 'angleInfo',

  SET_VIBRATION: 'setVibration',
  SEND_VIBRATION: 'sendVibration',

  SEND_SFX: 'sendSfx',

  CREATE_GAME: 'createGame',
  CREATE_GAME_SUCCESS: 'createGameSuccess',
  CREATE_GAME_CALLBACK: 'createGameCallback',
  JOIN_GAME: 'joinGame',
  JOIN_GAME_CALLBACK: 'joinGameCallback',
  START_GAME: 'startGame',
  EXIT_GAME_BY_HOST: 'exitGameByHost',
  EXIT_GAME_BY_HOST_CALLBACK: 'exitGameByHostCallback',
  EXIT_GAME_BY_GUEST: 'exitGameByGuest',
  EXIT_GAME_BY_GUEST_CALLBACK: 'exitGameByGuestCallback',
  EXIT_GAME_CALLBACK: 'exitGameCallback',
  LOAD_GAME_ROOM_LIST: 'loadGameRoomList',
  LOAD_GAME_INFO: 'loadGameInfo',
  ENGINE_ON: 'engineOn',
  SEND_GAME_DATA: 'sendGameData',
  FINISH_GAME: 'finishGame',
  FINISH_GAME_CALLBACK: 'finishGameCallback',
} as const;
